### ISSUE TITLE
Create events parser

### ISSUE THREAD

**Issue by ansivgit** [rolling-scopes/site#107] opened 2024-04-18 10:39 UTC
We need to create aggregator for the events in the section [Events](https://rollingscopes.com/#eventsl), formatted events-data and create list of events to display them in UI.

#### The main part of this task can be in two parts:

1. Create events parser from tg-channel [AfishaRSSchool](https://t.me/AfishaRSSchool);
2. Create data-formatter;
3. Create events aggregator for parsing events from different sources;

![Image](https://github.com/rolling-scopes/site/assets/56927722/04649c28-a2a4-4c74-8042-a6c97b6409c9)

**Comment by SpaNb4** [comment] 2024-07-05 13:36
Duplicate of https://github.com/rolling-scopes/site/issues/309

**Closed by SpaNb4** 2024-07-05 13:36 UTC
Labels: feature, proposal
